
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJWGQwQ1psYTRmNU13RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpBeU1qWXhNREV6TURWYUZ3MHpOakF5TWpReE1ERTRNRFZhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUQzRnkwSnVOcmw1b25VTnRueXpiK1p5RkJ3Umh4UE95RzFRRFZIQkhGdEZaeGd1dDNYSWJMY1RBaGsKV2d4QXNZdGE5U0ZqV0tnZGc5NWJBNG55QUhIVndaSmxKbWlMcTA2Uk1PRkVnTHg2Sm9SZmhMSnliVGdhM2RjdApmNlVNT3VXQ3hYN3ArOGhOTGhKNmxab1p6NXRCLy8wZjNObXpRdmFLbzZzdVhXWGNvOEFMa0h0Y2dWVnY3cUpuCjg3dnZFQ0p6ZHd5MGRpR3BweU45MkdRUlQxODlhSWgxM2x3dzlybE82eFc2NnVmVWl6T1pVZkJQMFhWeE5wUHgKM2lUWHNldHJoWlhzUHV2NXVBeWJpQTVuRFc3UGxSZGxQME9kMktqa3ZWK1N1YXc5cmlWL1B1YUN1VUdLc3FhRQpGVk9DSjZnQUh6N0FkZE5YcHVmektJRUtWbjJyQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJUQm51NHdEb2p2TjdqdGExUEdQNVFuOTczMWRUQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQUN2UWk4T0ppbApUb0huNFUxbDlpQjB3c2xxVFFyRkRHN2pnWjRWNVU0L1NXc2o5M1dmZEZjVGUzWDhSVHdTNXZRV3RvYUYrUDU1CkpVMExxaFJGVlBZanBJUXhlTVZpTnh6bjh6c3JGQWNmb1l2OXJXTmczR2FXemJJdjFRNGJndUVNVmxNN3BVOFEKZ2NYWGRoSXJYZHcvTkN5QktRTlFtYVViUUNLYXljN1ZvQ1l3aXdPRmpXRnY3dzVPWFFxOXMwRS91M1hRZHpzegpKV3BQWHR5cHV3ajdzSkNRMEZUMSt3SnZTUWRMSExjT2xFcE1JYS9HSjJkTWNPL3dRY0N2YXAwcU54T2NHZDZ3CktMN1I2T2YyanNPRFp4bC8xd0srMmMzT2I1eU5hQjBYQWdZZGFkYlBOZTlEWDFKM3JrdmplQUV5RXY5WDVjY2UKWVN3azdzZHZaOUoyCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://2d0a0d3a-e280-4a00-8d4a-0169482f6b39.us-west-1-gw.linodelke.net:443
  name: lke573391

users:
- name: lke573391-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IkdnQXYwMGEzb3FxSnNxbVViNnlYV3hlWlZwLVJ0OFkxNjNtUDJIaUJEMjAifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4tbTZxbGYiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiYTI2YmRjOTgtNWZiMi00ODQzLWIzYjUtZDVmY2ZlNDhiOTJjIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.dT1bvLgNsAuSb6f64iiHchcCxXLiJka5g0We56S0dGM7vmCbAibBr0iuz5w0GDWGZT4cyfZEq5ZqbvY834BG-UIpgWAKLPDjbB03NxP7k2-8HBG3IoibSwR3BWLClO6wkFlx8eimjkP87bNWtXGQZ4yYttYQFsNVtY7yXZ-NRFX8y0xeZZrJseU_B8ILDTQsipzydTCW0zaADT__w5yczXngfNnBJaCE--JZ472wpsdCSTymp84bywk88q9ZxMtAjN0EQ-n6ZRZn6w-5KCVRtjYZbYdn40g8Xsv7ab9IL_e_lnp2C7YptZCiFECFh8gQpa6fkHBxCgUwxQFOCHKRVQ

contexts:
- context:
    cluster: lke573391
    namespace: default
    user: lke573391-admin
  name: lke573391-ctx

current-context: lke573391-ctx
